### ISSUE TITLE
【在keepwork dashboard中】项目管理页面中，项目名称处有空格有时不能搜到结果

### ISSUE THREAD

**Issue by Kvaya** [tatfook/paracraft#100]
使用背景：
在项目管理页面中，项目名称、匹配情况下输入“黑与白 (BlackAndWhite)”未找到结果，随后掉“（BlackAndWhite）”，也未搜到结果，后来问开发原因，是因“黑与白”后面存在一个空格

解决方案：
建议“项目名称”处搜索框名称前后允许空格的情况

**Comment by Kvaya** [comment]
补充：在项目名称，匹配的情况下，搜“我从11楼跳下”搜不到结果

**Comment by Sandu1213** [comment]
> 使用背景：
> 在项目管理页面中，项目名称、匹配情况下输入“黑与白 (BlackAndWhite)”未找到结果，随后掉“（BlackAndWhite）”，也未搜到结果，后来问开发原因，是因“黑与白”后面存在一个空格
> 
> 解决方案：
> 建议“项目名称”处搜索框名称前后允许空格的情况

--以上需要的是允许前后存在空格的情况，目前只支持了后面空格的情况，请看看是否还需要调整
@Kvaya

**Comment by Sandu1213** [comment]
Dashboard release环境验证通过
