### ISSUE TITLE
首次分享世界成功后，还是显示没有分享

### ISSUE THREAD

**Issue by onedou** [tatfook/paracraft#114]
@LiXizhi commented on [Mon Feb 11 2019](https://github.com/tatfook/WorldShare/issues/118)

![image.png](https://images.zenhubusercontent.com/5925484051aa2c30577f488d/ab5a55cd-2cf7-4c82-ae1c-6daf9e4681fc)

分享成功后， 这里还是显示没有分享， 也无法查看分享链接。 

---

@onedou commented on [Mon Feb 11 2019](https://github.com/tatfook/WorldShare/issues/118#issuecomment-462197244)

可能没有获取到projectId

**Comment by Sandu1213** [comment]
已创建多个新世界进行分享验证，验证通过。 (test版本)
