### ISSUE TITLE
探索APP UI 效果改进1

### ISSUE THREAD

**Issue by Kvaya** [tatfook/paracraft#115]
背景：
探索APP 整体测试后，有些地方还需改进。年前版本测试1如下：
![ht5i5k70vo2cshgx6q6 c5a](https://user-images.githubusercontent.com/39363297/52924273-0a5c9b00-3367-11e9-8654-226e6fafe06d.png)

解决方案：
以上1.当金币数量为零时，点击世界进行查看或者游戏，这时提示用户去购买金币充值
设计稿如下：
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/85a8ed2f-93a2-4be9-82f2-2974321d6fe6)
补充说明：点击“去购买”，跳转至“设置密码”页面；

以上3.建议通过点击封面进行下载；

以上9.排序还是综合、最新、热门；排序规则还是跟现在KeepWork官网探索页面排序规则一样
![o1 x1 d2z c44 3d bmeg](https://user-images.githubusercontent.com/39363297/52924306-30823b00-3367-11e9-8a44-d17f556cc2a0.png)
备注：其他几点逐一修复

**Comment by Sandu1213** [comment]
问题1/3已经修复完成；
问题9的排序还是与预期的不同，请再调整

**Comment by Sandu1213** [comment]
已验证通过
