### ISSUE TITLE
【Bug-paracraft】当启用paracraft菜单后，再使用codeblock代码块时，会出现部分功能按钮被遮挡的情况，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/paracraft#124]
## The problem
当启用paracraft菜单后，再使用codeblock代码块时，会出现部分功能按钮被遮挡的情况，请调整

## Environment

* OS Info: Window10
* Version: V0.7.440
* model: codeblock

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.已存在账号且账号已登录
* Details:
1,选择任意一个自己创建的世界进入，然后打开菜单栏，启用锁定状态
2.再添加codeblock 代码块，然后对代码块进行编辑操作，观察paracraft页面显示

* Expected Result:
1.codeblock窗口与菜单栏窗口不存在覆盖的情况，codeblock窗口功能可用正常使用
* Actual Result:
1.codeblock窗口与菜单栏窗口存在重叠覆盖的情况。
 

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/278bb16e-b528-4db2-8d0c-458fcb6370f2)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/86c99f19-84c2-41dc-9313-2efc0affba93)

**Comment by LiXizhi** [comment]
![image](https://user-images.githubusercontent.com/94537/53158761-545fae00-35ff-11e9-8d2c-aeb3be96fd72.png)
Fixed in next release (已经修复，等下个版本发布. )  Thanks
