### ISSUE TITLE
【bug】世界-导出  功能失效

### ISSUE THREAD

**Issue by azothli** [tatfook/paracraft#125]
@azothli commented on [Fri Feb 22 2019](https://github.com/tatfook/Paraworld-Feedback/issues/29)

![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/25f33976-620a-4a18-a313-6d930417c6fb)
点击后没有任何反应

**Comment by LiXizhi** [comment]
![image](https://user-images.githubusercontent.com/94537/53728298-5f42fa00-3ead-11e9-8707-7a90ef455de4.png)
之前提示不明显， 换成messageBox了
