### ISSUE TITLE
帮助 致谢 的内容与一般理解不一致

### ISSUE THREAD

**Issue by azothli** [tatfook/paracraft#129]
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/89bccb96-7395-4e27-ac30-7cac44469faa)
帮助 致谢 的内容与一般理解不一致。
应该是我们表示感谢的人或组织。
当前是导航到sdk的首页了。

可以考虑
1. 去除
2. 做一个致谢的内容页面

**Comment by LiXizhi** [comment]
去掉了， 放到 关于 中了。 内容为：

https://keepwork.com/official/paracraft/credits
