### ISSUE TITLE
帮助 关于的内容 与惯例不同

### ISSUE THREAD

**Issue by azothli** [tatfook/paracraft#130]
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/2203f140-afe7-47fd-9b18-e721893f2d6a)

帮助 关于的内容，一般这个是版本信息、版权声明之类的
现在是外链的产品介绍，我们设计一个软件约定俗成的about吧

![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/ff4cc152-69ec-45a6-b559-a4975ad3479b)

**Comment by LiXizhi** [comment]
![image](https://user-images.githubusercontent.com/94537/53733656-9b318b80-3ebc-11e9-8581-90b9f7fabf73.png)
Fixed in next release (已经修复，等下个版本发布. )  Thanks
