### ISSUE TITLE
换装功能失效

### ISSUE THREAD

**Issue by azothli** [tatfook/paracraft#131]
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/b6770c2a-0186-431b-86f3-5475a8106eef)
换装功能失效

因为我们换了新的模型，不是以前的纸盒人，导致功能失效，建议保留功能，换成新的资源

然后该功能不放在菜单里，而是放在登录界面上。
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/7cee6b77-b0f2-4154-9ed0-30eb3ea15ef6)

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
