### ISSUE TITLE
创建新世界，默认名字编号不能自增

### ISSUE THREAD

**Issue by azothli** [tatfook/paracraft#132]
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/109aa49c-3b19-4a6a-8348-e392619aff59)

已有 默认名字2，再创建，应该是 默认名字3
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/365c4248-2651-45c7-8c7c-a7677431c4e4)

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
