### ISSUE TITLE
帮助  操作提示  与帮助功能重复，建议去除

### ISSUE THREAD

**Issue by azothli** [tatfook/paracraft#133]
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/c975c57a-6fb1-4382-aff4-aaf22c90627b)
帮助  操作提示，完全就是帮助系统的内容，在主UI上增加了一个卡通的入口。
感觉没有必要。

建议去掉。

**Comment by LiXizhi** [comment]
去掉了
