### ISSUE TITLE
帮助 快捷键 内容比较杂乱，待整理

### ISSUE THREAD

**Issue by azothli** [tatfook/paracraft#134]
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/3cc60e8d-b5af-46bd-b44d-e03537d50d71)

帮助 快捷键 内容比较杂乱，待整理
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/9a1c0f12-15ac-4795-879c-954ebd01a8d8)

**Comment by azothli** [comment]
`
<Items>
  <Type name="创造模式">
    <Item value="行动"desc=""/>
    <Item value="WASD"desc=""移动""/>
    <Item value="双击W不放"desc=""加速向前移动""/>
    <Item value="Shift+WASD"desc=""缓慢行走""/>
    <Item value="Space"desc=""跳跃/飞行""/>
    <Item value="F"desc=""进入/退出飞行模式""/>
    <Item value="F2"desc=""瞬移到跳转点""/>
    <Item value="Shift+F2"desc="瞬移到上一个跳转点"/>
    <Item value="点击鼠标中间"desc=""瞬间移动""/>
    <Item value="Tab"desc=""角色向上位移一层""/>
    <Item value="Shift+Tab"desc=""角色向下位移一层""/>
    <Item value="Shift"desc=""弯腰""/>
    <Item value="Q"desc=""扔掉手中的方块""/>
    <Item value="显示"desc=""/>
    <Item value="Ctrl+F12"desc=""隐藏界面UI""/>
    <Item value="F4"desc=""透明网格显示模式""/>
    <Item value="F11"desc=""全屏显示""/>
    <Item value="视角"desc=""/>
    <Item value="按住鼠标右键并移动"desc=""旋转视角""/>
    <Item value="~"desc=""打开望远镜""/>
    <Item value="F5"desc=""切换视角""/>
    <Item value="Ctrl+MouseWheel"desc=""调节摄影机距离""/>
    <Item value="Insert"desc=""摄像机拉远""/>
    <Item value="Delete"desc=""摄像机拉近""/>
    <Item value="Ctrl+Alt+PgUp"desc=""摄像机向上移动""/>
    <Item value="Ctrl+Alt+PgDn"desc=""摄像机向下移动""/>
    <Item value="编辑"desc=""/>
    <Item value="Ctrl+N"desc="新建"/>
    <Item value="Ctrl+O"desc="打开"/>
    <Item value="Ctrl+S"desc=""保存""/>
    <Item value="Ctrl+Z"desc=""撤销""/>
    <Item value="Ctrl+Y"desc=""重做""/>
    <Item value="Ctrl+C"desc=""复制""/>
    <Item value="Ctrl+X"desc=""剪切""/>
    <Item value="Ctrl+V"desc=""粘贴""/>
    <Item value="Del"desc="删除"/>
    <Item value="Shift+LeftClick"desc=""复制选中物品到新的位置""/>
    <Item value="建造"desc=""/>
    <Item value="点击鼠标右键"desc=""建造方块/触发机关""/>
    <Item value="点击鼠标左键"desc=""删除普通方块，长按删除交互方块""/>
    <Item value="Shift+RightClick"desc=""快速创建3个方块；在2个相同方块之间建立线（相隔不能大于19格）""/>
    <Item value="Shift+LeftClick"desc=""删除光标周围3x3x3的方块""/>
    <Item value="Alt+LeftClick"desc=""吸取场景中的方块替换手中方块""/>
    <Item value="Alt+RightClick"desc=""用手中方块替换场景中的方块""/>
    <Item value="Alt+Shift+RightClick"desc=""用手中方块替换场景中30格以内连续的同一方块""/>
    <Item value="Ctrl+LeftClick"desc=""进入物品高级属性界面；按住Ctrl键继续点击左键可选中一片区域的物品""/>
    <Item value="Ctrl+Shift+LeftClick"desc="选择所有与当前方块相连的方块"/>
    <Item value="Ctrl+D"desc=""返回上一次选区""/>
    <Item value="窗口"desc=""/>
    <Item value="Enter"desc=""打开聊天框""/>
    <Item value="E"desc=""打开物品栏""/>
    <Item value="B"desc=""打开背包""/>
    <Item value="/"desc=""输入命令行""/>
    <Item value="Esc"desc=""系统设置/退出""/>
    <Item value="F3"desc="系统信息"/>
    <Item value="F9"desc=""录制动画界面""/>
    <Item value="F1"desc="内置教程"/>
    <Item value="其他"desc=""/>
    <Item value="1~9"desc=""切换快捷物品栏""/>
    <Item value="滚动鼠标滚轮"desc=""切换快捷物品栏""/>
    <Item value="左键点击快捷物品栏"desc=""切换手中物品""/>
    <Item value="右键点击快捷物品栏"desc=""拖拽物品""/>
    <Item value="Ctrl+T"desc=""复制光标坐标信息""/>
    <Item value="Ctrl+R"desc=""复制光标离人物距离坐标""/>
    <Item value="F10"desc=""截图""/>
  </Type>
  <Type name="游戏模式">
    <Item value="行动"desc=""/>
    <Item value="WASD"desc=""移动""/>
    <Item value="双击W不放"desc=""加速向前移动""/>
    <Item value="Shift+WASD"desc=""缓慢行走""/>
    <Item value="Space"desc=""跳跃""/>
    <Item value="F2"desc=""瞬移到跳转点""/>
    <Item value="Shift"desc=""弯腰""/>
    <Item value="Shift+F2"desc="瞬移到上一个跳转点"/>
    <Item value="Q"desc=""扔掉手中的方块""/>
    <Item value="X"desc=""与最近的NPC对话""/>
    <Item value="显示"desc=""/>
    <Item value="Ctrl+F12"desc=""隐藏界面UI""/>
    <Item value="F4"desc=""透明网格显示模式""/>
    <Item value="F11"desc=""全屏显示""/>
    <Item value="视角"desc=""/>
    <Item value="按住鼠标右键并移动"desc=""旋转视角""/>
    <Item value="~"desc=""打开望远镜""/>
    <Item value="F5"desc=""切换视角""/>
    <Item value="Ctrl+MouseWheel"desc=""调节摄影机距离""/>
    <Item value="Insert"desc=""摄像机拉远""/>
    <Item value="Delete"desc=""摄像机拉近""/>
    <Item value="Ctrl+Alt+PgUp"desc=""摄像机向上移动""/>
    <Item value="Ctrl+Alt+PgDn"desc=""摄像机向下移动""/>
    <Item value="编辑"desc=""/>
    <Item value="Ctrl+N"desc="新建"/>
    <Item value="Ctrl+O"desc="打开"/>
    <Item value="Ctrl+S"desc=""保存""/>
    <Item value="建造"desc=""/>
    <Item value="点击鼠标左键"desc=""建造方块，触发机关""/>
    <Item value="点击鼠标右键"desc=""删除普通方块，长按删除交互方块""/>
    <Item value="窗口"desc=""/>
    <Item value="Enter"desc=""打开聊天框""/>
    <Item value="B"desc=""打开背包""/>
    <Item value="/"desc=""输入命令行""/>
    <Item value="Esc"desc=""系统设置/退出""/>
    <Item value="F3"desc="系统信息"/>
    <Item value="F9"desc=""录制动画界面""/>
    <Item value="F1"desc="内置教程"/>
    <Item value="其他"desc=""/>
    <Item value="1~9"desc=""切换快捷物品栏""/>
    <Item value="滚动鼠标滚轮"desc=""切换快捷物品栏""/>
    <Item value="左键点击快捷物品栏"desc=""切换手中物品""/>
    <Item value="右键点击快捷物品栏"desc=""拖拽物品""/>
    <Item value="F10"desc=""截图""/>
  </Type>
</Items>
`

**Comment by azothli** [comment]
http://qiniu.keepwork.com/d8b0b780-38ca-11e9-95af-3111b9a2f174.xml?e=4704677939&token=LYZsjH0681n9sWZqCM4E2KmU6DsJOE7CAM4O3eJq:Y1-lCgJxDnJEURH9lAT_rz6ceyY=#shortcutkey.xml

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
