### ISSUE TITLE
帮助 教学视频的网站待更新

### ISSUE THREAD

**Issue by azothli** [tatfook/paracraft#135]
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/7aa918d6-1f96-41a7-88b8-da934d43d424)

帮助 教学视频的网站待更新
现在是看起来比较随意的一个网站内容

**Comment by LiXizhi** [comment]
等文档站开发完毕

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
