### ISSUE TITLE
【ExplorerApp】Item UI 优化

### ISSUE THREAD

**Issue by onedou** [tatfook/paracraft#137]
LiXizhi 17:07:17
![image.png](https://images.zenhubusercontent.com/59df2959b0222d5de47b59a3/71364ec7-7cf3-4525-9bd8-fe2329294aca)
这个美术对齐的问题， 还要处理下。
 再网上几个像素。 然后项目ID最好可以点击，打开keepwork项目页面。 鼠标放上去有url tooltip

**Comment by Sandu1213** [comment]
对齐的问题另外跟进，其他已经修复
