### ISSUE TITLE
【ExplorerApp】优化 选择点击

### ISSUE THREAD

**Issue by onedou** [tatfook/paracraft#138]
![image.png](https://images.zenhubusercontent.com/59df2959b0222d5de47b59a3/af3118bb-ca43-4646-9f64-f578fb4cf0bc)
全部    已下载    用<div for="id">已下载  </div> 可以支持点文字，也是点按钮

**Comment by Sandu1213** [comment]
点击“全部游戏”文字，切换不了。
单点选项框，会出现如下情况：
![image](https://user-images.githubusercontent.com/21214285/53393867-76c74200-39d8-11e9-8218-99b2bb9c70b7.png)

**Comment by Sandu1213** [comment]
问题依旧

**Comment by onedou** [comment]
没有提交代码，应该可以了
