### ISSUE TITLE
ui应该遮蔽上面的点击操作

### ISSUE THREAD

**Issue by azothli** [tatfook/paracraft#141]
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/72dfc32d-9402-46d8-ba99-666dfa92fd12)

如图，我点击在ui上（非可点击元素），会对下面的块执行鼠标操作。
鼠标左键还是删除的功能，破坏很大。

这个应该是一个ui开发规范的问题，需要全部的ui都进行类似的处理。

**Comment by onedou** [comment]
![image](https://user-images.githubusercontent.com/3422640/53787827-0336af00-3f5b-11e9-97c8-73608cec8eb4.png)
