### ISSUE TITLE
【Bug-魔法哈奇】魔法哈奇注册的时候也需要绑定邮箱信息

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/paracraft#142]
## The problem
由于最近经常出现魔法哈奇用户无法找回密码的情况，排查后发现是注册时没有绑定邮箱信息，故需要调整一下注册绑定流程

## Environment
* OS Info: Window10
* TestObject：魔法哈奇
* Model:  注册

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常
* Details:
1.打开魔法哈奇进行注册，观察注册时是否需要邮箱信息

* Expected Result:
1.需要邮箱信息，会根据IP情况判断是否需要输入邮箱验证码
* Actual Result:
1.缺少邮箱信息
 

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/805f85ea-d50b-4a6e-ab1f-3ca9e62448af)

**Comment by Sandu1213** [comment]
@wxaxiaoyao 后端接口好了以后，请这里回复一下，谢谢。

**Comment by Sandu1213** [comment]
后台接口已经更新 (涉及IP的判断，需要客户端自己去处理，请知悉)
[地址](https://keepwork.com/keepwork/pwiki/dev/backend/keepworkAPI#%E6%B3%A8%E5%86%8C)
![image](https://user-images.githubusercontent.com/21214285/53550444-acebf980-3b71-11e9-9d6e-a878751378cd.png)

**Comment by LiXizhi** [comment]
![image](https://user-images.githubusercontent.com/94537/58008737-a0978d00-7b1f-11e9-831b-a52ad675dd62.png)

下个版本更新
