### ISSUE TITLE
paracraft，方块选择菜单，图标样式问题

### ISSUE THREAD

**Issue by azothli** [tatfook/paracraft#143]
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/8eab1e34-4f49-451c-a69a-e6426e6ff9f1)

由于没有外框，造成偏深色底的图标显示的很模糊，建议统一进行处理。
例如：都加一个底框

**Comment by LiXizhi** [comment]
试过 效果不是太理想

by design
