### ISSUE TITLE
E 菜单优化 关闭菜单的功能

### ISSUE THREAD

**Issue by azothli** [tatfook/paracraft#150]
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/cc470237-b416-42b6-b938-50f9fbcbfe3a)

目前有菜单栏靠边的按钮，但是没有这个贴边的功能，本质就是关闭。

去除贴边的按钮，使用正常的 关闭 按钮。

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
