### ISSUE TITLE
【Bug-explore App】探索App的界面内容需要支持i18n，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/paracraft#152]
@Sandu1213 commented on [Fri Mar 01 2019](https://github.com/tatfook/keepwork/issues/3850)

![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/86f477a1-3f00-4014-967e-bbe500e618d7)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/9f3352e1-c7f9-4b49-a67b-2733be36868b)
![image](https://user-images.githubusercontent.com/21214285/53621812-c43eeb80-3c32-11e9-8060-b1f905a33288.png)

---

@Sandu1213 commented on [Mon Mar 04 2019](https://github.com/tatfook/keepwork/issues/3850#issuecomment-469101624)

添加的EN 标签也需要支持能够正常显示出来，请再调整
![image](https://user-images.githubusercontent.com/21214285/53708024-6c8bc480-3e6c-11e9-9e5b-49a964716813.png)

---

@Sandu1213 commented on [Mon Mar 04 2019](https://github.com/tatfook/keepwork/issues/3850#issuecomment-469135433)

@onedou  big,目前英文标签功能已经支持了，请知悉

---

@onedou commented on [Tue Mar 05 2019](https://github.com/tatfook/keepwork/issues/3850#issuecomment-469507192)

好的，麻烦帮我建一个issue到paracraft项目 @Sandu1213 

---

@Sandu1213 commented on [Wed Mar 06 2019](https://github.com/tatfook/keepwork/issues/3850#issuecomment-469977324)

Ok

**Comment by Kvaya** [comment]
探索APP英文对应：
探索：Explore；
投币：Insert Coin;
返回：Back;
综合：Overall;
最新：Newest;
热门：Hottest;
项目ID：Project ID;
搜索：Search;
精选：Selected;
单人：Single-player;
双人：Two-player;
对战：Battle;
动画：Animations;
收藏：Favorites;

**Comment by Kvaya** [comment]
探索APP 英文：
探索：Explore；
投币：Insert Coin;
返回：Back;
综合：Overall;
最新：Newest;
热门：Hottest;
项目ID：Project ID;
搜索：Search;
精选：Selected;
单人：Single-player;
双人：Two-player;
对战：Battle;
动画：Animations;
收藏：Favorites;
多人：Multiplayer；
解谜：Riddles；
校园：Campus；
教学：Education；

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/54348904-15b09700-4685-11e9-863a-3d8ef78a10b3.png)

收藏的英文显示还需要调整

**Comment by onedou** [comment]
已更新，请pull npl paracraft package

**Comment by Sandu1213** [comment]
已经按照[地址](https://github.com/tatfook/ParacraftBuildinMod)上的方法1，更新了paracraft package.但是也没还是显示中文，请再排查

![image](https://user-images.githubusercontent.com/21214285/55372132-35740600-5533-11e9-89d2-79db7d38be37.png)
