### ISSUE TITLE
电影方块：放弃创建角色

### ISSUE THREAD

**Issue by azothli** [tatfook/paracraft#155]
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/a2e33236-cf0d-4bf0-9735-0bef3aa50d28)

关闭窗口放弃创建角色的时候，应该终止创建，而不是自动创建一个

![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/2952557c-7ced-492e-9028-4e318935c81a)

**Comment by LiXizhi** [comment]
相当于已经创建了。 又显示了人物属性

by design.
