### ISSUE TITLE
电影方块：切换时间轴的内容

### ISSUE THREAD

**Issue by azothli** [tatfook/paracraft#156]
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/8085a20b-e15b-4931-b01a-a28b8528231a)
这里是一个下拉表单，没有任何标识的话，不好理解这里有扩展的内容。
建议调节为常见的控件样式
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/603f72ea-d0dc-4c81-891a-1873d444766a)

**Comment by azothli** [comment]
![image](https://user-images.githubusercontent.com/22001356/54345497-24478000-467e-11e9-8e08-3acde03f0a12.png)

**Comment by LiXizhi** [comment]
暂时不改了。 整体风格
