### ISSUE TITLE
电影方块：时间轴起止时间输入的提示

### ISSUE THREAD

**Issue by azothli** [tatfook/paracraft#157]
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/3d9b1c4b-951d-4b42-9a4d-1486766c1cfd)
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/c6657f8e-6055-4f58-a2b7-527bafbff976)
这两个区域，mouseover需要添加提示

时间轴起始时间（秒）
时间轴终止时间（秒）

**Comment by LiXizhi** [comment]
@
Fixed in next release (已经修复，等下个版本发布. )  Thanks
