### ISSUE TITLE
电影方块：角色对应时间轴菜单的调整

### ISSUE THREAD

**Issue by azothli** [tatfook/paracraft#158]
1 调整了内容顺序，按照相关性进行了排列
2 调整了快捷键，去除了类似 33 这样的快捷键
3 调整了菜单中快捷键的提示方式

![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/49bc1771-5fc7-42d2-bf29-79fd95e18b61)

![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/8b79d52a-7897-43eb-bd01-3ae34774c910)

**Comment by LiXizhi** [comment]
部分优化了
Fixed in next release (已经修复，等下个版本发布. )  Thanks
