### ISSUE TITLE
电影方块：时间度量单位，统一为秒

### ISSUE THREAD

**Issue by azothli** [tatfook/paracraft#159]
现在的单位有秒，有毫秒（毫秒对于电影制作来说有些过于小了）
建议统一使用秒，用户在输入的时候，我们可以支持到毫秒级别（0.001）
这样大家在设定时间的时候，可以选择使用如：
2.4
而不是2400

![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/f9c59a4e-bb91-4539-9507-db706f79e864)
主要就是这里的问题，其他地方都是秒

**Comment by LiXizhi** [comment]
要精确到帧， 只能先这样
