### ISSUE TITLE
电影方块：时间轴设定

### ISSUE THREAD

**Issue by azothli** [tatfook/paracraft#160]
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/d2008d3e-df75-4716-af77-2e0f80ca40bc)
时间轴的时间区域，右键可以直接转化为输入框，灰度显示当前时间，等候用户输入。
输入后+回车，跳转到对应的时间点
esc 取消输入
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/383d119d-a872-4469-9c51-22723cb87526)

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
