### ISSUE TITLE
【Bug-paracraft】英文模式下，菜单栏的上传世界显示不合理且功能不可用

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/paracraft#161]
## The problem
英文模式下，菜单栏的上传世界显示不合理且功能不可用

## Environment

* OS Info: Window10
* paracraft version:0.7.449
* Model:  i18n /share world

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，已存在账号且账号已登录
* Details:
1.设置系统语言为English，然后进入world，按“ESC”打开菜单栏，观察上传世界按钮显示情况
2.点击上传世界，观察世界是否可以正常上传

* Expected Result:
1.可以正常上传且页面显示合理
* Actual Result:
1.页面显示不合理且功能不可用
 

## Attachments (eg:logs/video/screenshot)
![image](https://user-images.githubusercontent.com/21214285/54348454-05e48300-4684-11e9-94bf-ad740a21908d.png)

**Comment by onedou** [comment]
![image](https://user-images.githubusercontent.com/3422640/54656932-8bdc5000-4b02-11e9-87b2-16445ace82c9.png)
最新版已经支持，请重新测试
