### ISSUE TITLE
电影方块：默认的命令序列

### ISSUE THREAD

**Issue by azothli** [tatfook/paracraft#162]
问阿杰，好像极少用，基本用不到，可以考虑去除
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/afedceac-fc24-498f-8193-13fd8fc382a3)

**Comment by LiXizhi** [comment]
没有摄影机时， 需要这个。 虽然有摄影机时，去掉更好些。 但是逻辑上， 字幕这些都是记录在这个角色上的。
