### ISSUE TITLE
paracraft主ui增加npl大赛入口

### ISSUE THREAD

**Issue by azothli** [tatfook/paracraft#167]
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/11aba5cd-4e76-48b6-ae03-758690ba2899)

增加一个npl大赛的icon

**Comment by enya-i** [comment]
![Uploading C4F48F0C5FFBC5E12497DC92149A81AA.jpg…]()

**Comment by ouyc** [comment]
![{5D5DEBB7-1753-4826-5215-1815A2A10809}](https://user-images.githubusercontent.com/38035998/54741734-4b5ffd80-4bfa-11e9-8455-199094da6db9.jpg)

**Comment by LiXizhi** [comment]
目前在加载世界中有了。 上面还是以APP为主。
