### ISSUE TITLE
cad模块：形状命名错误

### ISSUE THREAD

**Issue by azothli** [tatfook/paracraft#172]
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/f6daf9d2-9c63-4586-bd12-25173f3093b2)

等边的叫      立方体，或者正方体    是一种东西
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/06f00d84-7f67-4719-95d5-4a7ecf3622fd)

不等边的叫长方体
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/946968ef-8a3e-4bd6-a0cd-329b7ce6c283)

**Comment by zhangleio** [comment]
已修正，把 “立方体” 改为 “长方体”了。
