### ISSUE TITLE
esc菜单优化：添加另存为 功能

### ISSUE THREAD

**Issue by azothli** [tatfook/paracraft#176]
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/c79e6488-2e69-4dac-acfa-38f3597ce47e)

如果当前世界为只读世界，则将“保存世界”按钮，变化成“另存世界”

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
