### ISSUE TITLE
退出UI调整

### ISSUE THREAD

**Issue by azothli** [tatfook/paracraft#177]
将打分功能从浏览过程中转移到退出时。
浏览3分钟不再有评分提醒。
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/015138e3-9bbb-46c0-af82-0c8563857b1a)
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/e1449a12-3fc9-4b30-ae7c-319f392b2c0c)
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/ff432696-d65b-486d-8905-bd93d5f6ebcf)
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/d20a28e8-fff1-4a43-b810-4ff970c3606f)

**Comment by azothli** [comment]
用来替换这个，用现有的paracraft ui元素，需要设计下比例位置
![image](https://user-images.githubusercontent.com/22001356/57498819-fdb96480-730f-11e9-844a-e4aec821dc66.png)

**Comment by azothli** [comment]
需要登录才可以进行的操作，点击弹出登录窗口就好。

**Comment by dalin00** [comment]
![I拥有者-已分享](https://user-images.githubusercontent.com/24222876/57512829-5e13ca80-733f-11e9-962c-b2ed2ee0037e.jpg)
![访问者-未打分](https://user-images.githubusercontent.com/24222876/57512836-62d87e80-733f-11e9-9815-2f9202706fd1.jpg)
![访问者-已打分](https://user-images.githubusercontent.com/24222876/57512842-64a24200-733f-11e9-9c8f-fb51410915e2.jpg)
![拥有者-未分享 ](https://user-images.githubusercontent.com/24222876/57512847-65d36f00-733f-11e9-8724-a889190302dc.jpg)

**Comment by dalin00** [comment]
![I拥有者-已分享](https://user-images.githubusercontent.com/24222876/57512829-5e13ca80-733f-11e9-962c-b2ed2ee0037e.jpg)
![访问者-未打分](https://user-images.githubusercontent.com/24222876/57512836-62d87e80-733f-11e9-9815-2f9202706fd1.jpg)
![访问者-已打分](https://user-images.githubusercontent.com/24222876/57512842-64a24200-733f-11e9-9c8f-fb51410915e2.jpg)
![拥有者-未分享 ](https://user-images.githubusercontent.com/24222876/57512847-65d36f00-733f-11e9-8724-a889190302dc.jpg)
