### ISSUE TITLE
【bug】创建新世界，设置了世界名称后，又修改了初始地形，之前设置好的世界名称会消失掉。

### ISSUE THREAD

**Issue by shirleyluo1130** [tatfook/paracraft#179]
![image.png](https://images.zenhubusercontent.com/5b334100945e4824d962bd68/1b466cb8-01d3-43d4-81e8-ac5b2ae74337)

**Comment by Sandu1213** [comment]
目前手机端是可以的，但PC端还是不对，切换地形后，还是会将用户已经设置好的名称替换为默认名称了，请再调整。

**Comment by onedou** [comment]
修复pr合并后可以测试
https://github.com/NPLPackages/paracraft/pull/55
