### ISSUE TITLE
课程功能中按钮更新

### ISSUE THREAD

**Issue by azothli** [tatfook/paracraft#181]
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/f3950e84-70e4-4ec9-bf7d-e44986417d40)

![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/dbc7b877-9418-45c8-aa34-2e0883f4f00a)

文字调整为“更多”
url调整为
https://keepwork.com/official/docs/index

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
