### ISSUE TITLE
局域网自动找主机的功能

### ISSUE THREAD

**Issue by onedou** [tatfook/paracraft#185]
![image](https://user-images.githubusercontent.com/3422640/58775414-f0825380-85f7-11e9-8ef9-532ee14434d4.png)

**Comment by onedou** [comment]
未知接口

**Comment by LiXizhi** [comment]
1. 通过UDP广播， 自动列出局域网中的主机。 在 输入project id 的`...`按钮中。
2. 提供指令+特殊物品： 让主机老师可以操作：比如召唤或广播消息。 
-----

另起一个issue:  自动主机加入房间功能。 Class id, project id相同的人， 可以考虑进入一个房间。
