### ISSUE TITLE
paaracraft，软件封面调整

### ISSUE THREAD

**Issue by azothli** [tatfook/paracraft#186]
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/aeb4b038-4640-4e24-8f7e-50f3dda768e1)

去掉“学会编程，学会学习”这句指代不明，无法很好传达我们理念的宣传语

去掉“点击任意位置继续”，视觉不够突出，需要阅读才能找到
将次功能，调整为按钮“点击开始”，参考图片中的比例位置，用程序生成。

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
