### ISSUE TITLE
【Bug-paracraft】mac版分享时，对已分享过的项目点击浏览按钮，发现打开页面不对

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/paracraft#202]
### Details：
   1.打开一个已经上传过的世界，进入世界后，按“ESC”调出分享菜单，然后点击“浏览”按钮，观察打开的页面是否正确
[点击查看截图](https://api.keepwork.com/storage/v0/siteFiles/4404/raw#image.png)

**Comment by onedou** [comment]
西峙说是正常的
