### ISSUE TITLE
登录框记录多个账号

### ISSUE THREAD

**Issue by onedou** [tatfook/paracraft#203]
![image.png](https://images.zenhubusercontent.com/59df2959b0222d5de47b59a3/5bedb787-7655-4d6d-a327-43331ac42ec9)

**Comment by dalin00** [comment]
![登录](https://user-images.githubusercontent.com/24222876/61212396-bea2f780-a734-11e9-8ffc-002f4e980a32.jpg)
![登录-记住多个账号](https://user-images.githubusercontent.com/24222876/61212398-bf3b8e00-a734-11e9-9d2b-609beb754e89.jpg)
