### ISSUE TITLE
【Bug-paracraft】开启多人联网功能后，在主机侧设置图片后，在其他机器上不能同步展示，请优化

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/paracraft#210]
## The problem
开启多人联网功能后，在主机侧设置图片后，在其他机器上不能同步展示，请优化

## Environment
* OS Info: Window10
* App Version : paracraft 
* Model:  多人联网

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，已开启多人联网功能
* Details:
1.用户A在多人世界里，添加了一个相框，然后设置图片后，再切换到用户B的世界里进行观看

* Expected Result:
1.图片可以正常展示，因为处于同一个世界
* Actual Result:
1.图片缺少展示，需要手动再去设置
 

## Attachments (eg:logs/video/screenshot)
![pic_lost.jpg](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/13219a19-ef62-4cab-a39c-17a6d161e0a2)

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
