### ISSUE TITLE
【Bug-多人联网】多人联网时，如果使用“金币”或“飞翔的心”，就只能使用者自身才能看到

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/paracraft#211]
## The problem
多人联网时，如果使用“金币”或“飞翔的心”，就只能使用者自身才能看到

## Environment

* OS Info: Window10
* App version:paracraft v0.7.467
* Model:  多人联网

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.多人联网功能已开启
2.已有多个用户进入同一世界
* Details:
1.用户A进入世界后使用“金币”或者“飞翔的心”进行创建
2.其他用户查看世界时，观察是否可以看到该物品
* Expected Result:
1.用户可以看到这些物品
* Actual Result:
1.用户看不到该类物品
 

## Attachments (eg:logs/video/screenshot)
![gold_show.jpg](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/fcb0860f-93f4-40d9-8315-fe8941d09b91)

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
