### ISSUE TITLE
【Bug-paracraft】代码方块及CAD方块的图块功能不能使用，出现空白情况，请尽快修复

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/paracraft#214]
### Steps:
1.在MAC上打开paracraft，使用代码方块，选择"图块“模式进行编程，观察效果
2.在window上打开paracraft，选择CAD方块，使用”图块“模式进行编码，观察效果

**Result:**
都会出现空白页面，请调整

**Attachment:**
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/28a57e47-7704-4f60-94a6-7633c96e03b7)

**Comment by onedou** [comment]
0.7.469 版本测试
