### ISSUE TITLE
【Bug-Paracraft】多人联网模式下，去调整角色的造型，调整后只能本机看到效果

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/paracraft#222]
### Details:
  1.打开多个客户端，先用其中一个客户端开启多人联网功能，然后其他客户端连入主机
  2.然后按ESC打开菜单栏，选中“换装”->“更改造型”，更改造型后，再观察其他机器上显示情况

![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/b3b23655-1244-4e78-bbfd-6c6317e15e61)

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
