### ISSUE TITLE
【天梯】Paracraft作品评分功能

### ISSUE THREAD

**Issue by azothli** [tatfook/paracraft#23]
![image](https://user-images.githubusercontent.com/22001356/50764798-d776b000-12ae-11e9-840a-880493d4fd96.png)

需要已登录，且为实名用户。
用户在作品中停留3分钟的时候，弹出评分提示按钮，点击打开评分ui
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/75e47fd8-4e46-442e-b4a4-3e5d92567b6b)

![image](https://user-images.githubusercontent.com/22001356/50764728-a39b8a80-12ae-11e9-92f5-fae3b4dc5c64.png)

打了3颗星
![image](https://user-images.githubusercontent.com/22001356/50764762-bc0ba500-12ae-11e9-87ea-16d4f26655c5.png)

参考天猫的评分体验，那个实心的星星代表选择的状态
需要为作品至少打1颗星
选择不同的星星数量，请打分的位置替换成不同的话语
5     震撼人心
4     印象深刻
3     感觉还行
2     十分普通
1     不怎么样

每一颗星星代表20分
最终结果是百分制，最高100分，最低10分

确定后提交（用户对一个作品仅有一次打分机会），执行打分奖励，给出提示
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/cd10a2d1-6f53-4429-a48c-dbc69f655c6d)
点击稍后再说的话，则关闭评分ui，然后每5分钟给一次评分入口的提醒

**Comment by leopoldchen** [comment]
@wxaxiaoyao 需要给项目加一个评分记录的表，记录每个人对某个项目的评分，项目表里需要加个count，记录总评价数

**Comment by Sandu1213** [comment]
目前任务系统还没有完工，所以涉及奖励的部分可以先屏蔽（已和产品沟通，达成一致）
![image](https://user-images.githubusercontent.com/21214285/51368004-41514e00-1b28-11e9-90c7-293e2b019417.png)
