### ISSUE TITLE
建议增加出生点位置数量，或者是增加地图到达功能。

### ISSUE THREAD

**Issue by grandlin** [tatfook/paracraft#230]
由于以后学生会一直在一个场景里面建造和做动画，随着课程进度，场景内会越来越多物品，包括一些BAX原始模型。后期肯定会遇到迷路找不到场景的问题，这个问题可能也会难住很多老师。
建议增加/home的数量，或者是现有的地图模块能否进行优化，可以展现出场景世界里哪块有物品，然后可实现一键传送功能。

**Comment by Sandu1213** [comment]
同之前何老师反馈的问题类似，需要一个可以快速找到学生及将学生快速集中起来的功能

**Comment by LiXizhi** [comment]
这个功能已经有了： 快捷键 Ctrl+F         
可以立即传送到场景中的告示牌。

**Comment by grandlin** [comment]
棒！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Li, Xizhi <notifications@github.com&gt;
发送时间: 2019年9月9日 14:06
收件人: tatfook/paracraft <paracraft@noreply.github.com&gt;
抄送: grandlin <1520288484@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[tatfook/paracraft] 建议增加出生点位置数量，或者是增加地图到达功能。 (#230)




这个功能已经有了： 快捷键 Ctrl+F
 可以立即传送到场景中的告示牌。
