### ISSUE TITLE
图块化编程界面无法切换代码方块

### ISSUE THREAD

**Issue by grandlin** [tatfook/paracraft#236]
![image](https://user-images.githubusercontent.com/53553316/64243441-ef83f980-cf39-11e9-8df6-09dcb63a65a6.png)
![image](https://user-images.githubusercontent.com/53553316/64243459-f7439e00-cf39-11e9-9a70-e37467e0ca5c.png)

**Comment by LiXizhi** [comment]
内置浏览器短期内没有很好的方案
