### ISSUE TITLE
建议新增切换默认编程窗口

### ISSUE THREAD

**Issue by grandlin** [tatfook/paracraft#237]
由于未来机构的学员会有长时间、高频率的使用“图块”代码编程来学习和创作，建议这里能新增一个切换默认显示“图块”或“代码”界面的功能。
![image](https://user-images.githubusercontent.com/53553316/64243851-9ff1fd80-cf3a-11e9-84de-41f199f505fa.png)

**Comment by LiXizhi** [comment]
会自动记住你上次的选项的。应该推荐用户多看代码。

this is by design.
