### ISSUE TITLE
关于代码方块的功能讨论

### ISSUE THREAD

**Issue by grandlin** [tatfook/paracraft#239]
需要新增的两个图块功能：
1.改变环境中的时间
2.真实光影模式的切换
3.光源颜色的切换
另外，碰撞功能需要优化，需求是：以乒乓球为例，学生把球板导入场景后放大，如何实现较为精准的碰撞？而不是只碰撞中间一个方块的位置？

**Comment by LiXizhi** [comment]
123已经解决了。  ，碰撞功能需要优化单独一个Issue吧

**Comment by grandlin** [comment]
好的，收到！辛苦你了！





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Li, Xizhi <notifications@github.com&gt;
发送时间: 2019年9月19日 20:29
收件人: tatfook/paracraft <paracraft@noreply.github.com&gt;
抄送: grandlin <1520288484@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[tatfook/paracraft] 关于代码方块的功能讨论 (#239)




123已经解决了。  ，碰撞功能需要优化单独一个Issue吧
