### ISSUE TITLE
联机时，含羞草无法使用

### ISSUE THREAD

**Issue by grandlin** [tatfook/paracraft#246]
联机状态时，服务器无法编辑已创建的含羞草，只能新建，且新建后只能编辑一次，而编辑后的代码亦无法激活使用。
学生的电脑也无法激活含羞草里面的代码，无论是自己创建的，还是服务器创建的。

**Comment by LiXizhi** [comment]
是否你使用的是旧的版本。 我这个测试都可以反复编辑。 和激活。 可以找测试人员帮忙复现。
