### ISSUE TITLE
联机时，Ctrl+F无法有效使用

### ISSUE THREAD

**Issue by grandlin** [tatfook/paracraft#247]
问题描述：
1.主机加载“TEXT”标签牌比较慢，并且有丢失的情况。
2.其他联机者也无法完整显示标签内容，目前测试出来的问题是，如果角色（主机或联机者）离标签较远，系统就不会读取这个标签的信息，导至CTRL+F列表没有显示。如果世界比较大，这个标签将失去意义。

**Comment by LiXizhi** [comment]
2. Ctrl+F为本地搜索， 客户端不能搜索服务器的数据。 
1.主机加载“TEXT”标签牌比较慢，并且有丢失的情况： 这个无这里无法复现， 请找 测试 写具体测试步骤。 单独建立issue.
