### ISSUE TITLE
建议在操作界面新增三维坐标，以方便确定移动或搭建的方向

### ISSUE THREAD

**Issue by grandlin** [tatfook/paracraft#252]
如题。
示意图：
![image](https://user-images.githubusercontent.com/53553316/65480892-c534b480-dec5-11e9-93ff-9ff8012baf43.png)

**Comment by grandlin** [comment]
![V JIOU5AL_T8F{$A5A`0QDK](https://user-images.githubusercontent.com/53553316/67540105-cc462100-f716-11e9-98d6-c9f019cb5540.png)

**Comment by grandlin** [comment]
参考视频链接：https://api.keepwork.com/storage/v0/siteFiles/7924/raw#QQ视频20191025110239.mp4

**Comment by LiXizhi** [comment]
按Ctrl+左键，就可以看到位置了。 位置用F3看。 
![image](https://user-images.githubusercontent.com/94537/67541947-5b563780-f71d-11e9-992f-ef3fb907777f.png)

这个比较影响显示， 暂时先不加了。
