### ISSUE TITLE
电影片段的角色换肤功能无法正常使用

### ISSUE THREAD

**Issue by grandlin** [tatfook/paracraft#256]
如题，
![image](https://user-images.githubusercontent.com/53553316/65830295-c0666b00-e2e0-11e9-80e7-0ef55a133793.png)
![image](https://user-images.githubusercontent.com/53553316/65830334-11765f00-e2e1-11e9-9b01-1255e718bcf3.png)
点确定后仍退回原来的造型。

**Comment by LiXizhi** [comment]
这种操作方式都被发现了。不支持在这里换。只能在时间轴上换。

**Comment by grandlin** [comment]
哈哈，一般都习惯这么操作的。
在时间轴上只能换模型，无法换皮肤，在皮肤轴里没有内置的皮肤可以选择。
![image](https://user-images.githubusercontent.com/53553316/65831410-a5e5bf00-e2eb-11e9-8348-ab1aad0ef11d.png)
