### ISSUE TITLE
急：关于代码方块中“循环指令”的运行逻辑问题

### ISSUE THREAD

**Issue by grandlin** [tatfook/paracraft#259]
如图：
循环指令正常的运行逻辑应该是像橙色箭头一样，依次循环运行“重复”里面的指令，但现在的运行逻辑是像红色箭头所示，只执行”重复“里面的一个指令。
![微信截图_20191010104832](https://user-images.githubusercontent.com/53553316/66535504-56ee2400-eb4c-11e9-9536-76c6e05c2395.jpg)

**Comment by grandlin** [comment]
![image](https://user-images.githubusercontent.com/53553316/66537331-9b7cbe00-eb52-11e9-8085-30ba3011272e.png)

![image](https://user-images.githubusercontent.com/53553316/66537506-3ecdd300-eb53-11e9-8a90-f84b8b9d02d3.png)

**Comment by grandlin** [comment]
[https://api.keepwork.com/storage/v0/siteFiles/7741/raw#微信截图_20191010104832.jpg](url)

**Comment by LiXizhi** [comment]
我看下， 这个是clone命令的逻辑问题。 没有注意这个细节。 先用其它写法吧。

**Comment by LiXizhi** [comment]
![image](https://user-images.githubusercontent.com/94537/67027198-b85d5680-f13b-11e9-9ab0-f473fcc19c6b.png)
Fixed in next release (已经修复，等下个版本发布. )  Thanks
