### ISSUE TITLE
PAC英文版的翻译问题

### ISSUE THREAD

**Issue by grandlin** [tatfook/paracraft#260]
英文版的工具界面，标签部分仍然显示的是中文版。
![image](https://user-images.githubusercontent.com/53553316/66590596-b76c7800-ebc3-11e9-8c1e-b6d08667297b.png)

**Comment by LiXizhi** [comment]
之前需要重启。刚刚已经改为不用重启了。 
Fixed in next release (已经修复，等下个版本发布. )  Thanks
