### ISSUE TITLE
增加世界改名的功能

### ISSUE THREAD

**Issue by azothli** [tatfook/paracraft#276]
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/de873deb-915f-4bb1-bde5-ae285b9b9922)
点击后，名字变为文本输入框，内容为当前名字，输入框获得焦点
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/ef6d6398-c5d8-4dec-aeab-d462d83afe3f)

回车确认
移除焦点确认、
注意检测名称格式
注意关键字过滤

**Comment by dalin00** [comment]
干旱量

**Comment by dalin00** [comment]
![增加世界改名的功能 ](https://user-images.githubusercontent.com/24222876/67365730-b87aad80-f5a4-11e9-820a-768309611335.jpg)
