### ISSUE TITLE
代码岛的“定位点”功能逻辑参考

### ISSUE THREAD

**Issue by grandlin** [tatfook/paracraft#277]
这个“定位点”的功能值得参考，能解决掉一些“面向”、“跟随”的需求。定位点不仅可以设置，还可以改变定位点前移或后移位置，使用起来会让学生更方便。
具体请看一下这个2分钟的视频：https://api.keepwork.com/storage/v0/siteFiles/7925/raw#定位点.mp4

**Comment by LiXizhi** [comment]
这个好像没有什么用。 没有必要多一个概念。 
你如果需要这个功能，就再创建一个代码角色名字叫“定位点”即可。效果是一模一样的。
