### ISSUE TITLE
关于“K”键设置关键帧的问题

### ISSUE THREAD

**Issue by grandlin** [tatfook/paracraft#284]
在位置轴按“K”键K关键帧时，1、3、4轴同时都K了，反过来在其他轴按“K”键同样影响到其他不相关轴的关键帧。
主要影响的问题是，在2、3、4轴K帧后，影响到了“动作轴”，导致本来没动作的人物在播放时持续抖动，播放待机动作
![image](https://user-images.githubusercontent.com/53553316/68935334-6dcf0880-07d3-11ea-9ada-67d3c8b27987.png)
![image](https://user-images.githubusercontent.com/53553316/68935392-850df600-07d3-11ea-9872-e6046bac1e81.png)

**Comment by LiXizhi** [comment]
好的， 当时主要是给另外一中拍摄方式做的。 目前用的不多了。 我去掉即可。 

Fixed in next release (已经修复，等下个版本发布. )  Thanks
