### ISSUE TITLE
物理碰撞代码参考

### ISSUE THREAD

**Issue by grandlin** [tatfook/paracraft#285]
编程猫的编辑器里有一个这功能列表，挺好的，可能参考一下：
![image](https://user-images.githubusercontent.com/53553316/68936904-65c49800-07d6-11ea-97e5-a938652fac4a.png)
![image](https://user-images.githubusercontent.com/53553316/68936924-6d843c80-07d6-11ea-88c1-a60839d81385.png)
![image](https://user-images.githubusercontent.com/53553316/68936936-7117c380-07d6-11ea-860a-ef909109b33d.png)

**Comment by LiXizhi** [comment]
好的， 这些之前都可以通过命令实现， 我加到代码方块中的设置属性中吧

**Comment by LiXizhi** [comment]
![image](https://user-images.githubusercontent.com/94537/70683986-6b32d680-1cdf-11ea-9ac0-2172d89ee979.png)
Fixed in next release (已经修复，等下个版本发布. )  Thanks


常用的都加了。 力用速度模拟就可以了。 
反弹用的不多， 用代码处理即可。
