### ISSUE TITLE
【优化建议】部分动物在水里隐藏了，不明原因

### ISSUE THREAD

**Issue by grandlin** [tatfook/paracraft#286]
目前试了鲸鱼、海豚都出现 这种问题：
如图：
![image](https://user-images.githubusercontent.com/53553316/69039944-e7f7cb00-0a27-11ea-9c8c-498b46489855.png)
![image](https://user-images.githubusercontent.com/53553316/69039975-f47c2380-0a27-11ea-94b8-2b32d75a1a61.png)
![image](https://user-images.githubusercontent.com/53553316/69039981-f80faa80-0a27-11ea-89e3-0548c40f9d9b.png)
![image](https://user-images.githubusercontent.com/53553316/69040189-5e94c880-0a28-11ea-95f4-e58722b216e9.png)

**Comment by grandlin** [comment]
还出现了"剁椒鱼头"的特效^-^
![image](https://user-images.githubusercontent.com/53553316/69040445-c6e3aa00-0a28-11ea-9e69-efca824de038.png)

**Comment by grandlin** [comment]
![image](https://user-images.githubusercontent.com/53553316/69040666-23df6000-0a29-11ea-8b9d-e9f3b6449312.png)

**Comment by Sandu1213** [comment]
问题可以复现，可能与能见度的角度有关，拉近镜头还是比较容易看到完整的。

**Comment by Sandu1213** [comment]
可以参考项目ID： 4025

**Comment by LiXizhi** [comment]
模型本身的材质当时做的时候有问题 （应该是不透明的， 结果目前是透明材质）。 暂时没有好的办法。 
用其他正确的模型吧。
