### ISSUE TITLE
“隐藏”图块的功能问题

### ISSUE THREAD

**Issue by grandlin** [tatfook/paracraft#287]
“隐藏”图块功能无法直接使用，必须上面搭配“时间”，否则无法生效。如图：
![image](https://user-images.githubusercontent.com/53553316/69040831-76b91780-0a29-11ea-84b9-f743699589f7.png)
![image](https://user-images.githubusercontent.com/53553316/69040849-7de02580-0a29-11ea-823a-e3b4ffa3be18.png)

**Comment by LiXizhi** [comment]
这里我不敢改，因为很多旧项目，不是这个逻辑。 
目前clone命令， 并不会复制hide属性。
