### ISSUE TITLE
界面左侧的绿色圆圈能否隐藏？

### ISSUE THREAD

**Issue by grandlin** [tatfook/paracraft#288]
如图：
![image](https://user-images.githubusercontent.com/53553316/69125510-ea6a2b80-0ae0-11ea-8f26-94a1b49a8beb.png)

![image](https://user-images.githubusercontent.com/53553316/69125559-07066380-0ae1-11ea-9b9d-a09390917281.png)
这个圈子可否隐藏？在录制影片的时候经常会出现，影响美观。。。

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
