### ISSUE TITLE
关于代码建模的建议

### ISSUE THREAD

**Issue by grandlin** [tatfook/paracraft#289]
我们软件可以通过“代码指令”直接生成模型，是否能把这个功能封装到代码模块里面？
《我的世界》教育版没试过，但《迷你世界》、《代码岛》均可实现通过代码直接生成模型。
例如：
![image](https://user-images.githubusercontent.com/53553316/69312883-144f5980-0c6b-11ea-85a5-7c119fa0c0e4.png)

**Comment by LiXizhi** [comment]
这些功能，我们全部用命令行支持了。 基本函数集合越小越好。 
让用户学习看命令， 和使用命令吧。 对它们帮助大。 

如果只是为了课程， 可以做一个类似楚汉争霸的游戏， 里面有这些。

**Comment by grandlin** [comment]
好的，收到
