### ISSUE TITLE
【优化建议】目前检测碰撞的效果不好，请优化

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/paracraft#293]
![image](https://user-images.githubusercontent.com/21214285/69337010-ceaa8500-0c9a-11ea-8427-b9c4386e321f.png)

**Comment by LiXizhi** [comment]
图中的问题， 应该已经解决了， 是否更新到最新版本了？ 

目前所有物体的碰撞半径默认为0.25米.  可以用程序改
