### ISSUE TITLE
“创建变量”之后无法在“变量名”模块下使用

### ISSUE THREAD

**Issue by grandlin** [tatfook/paracraft#295]
“创建变量”之后无法在“变量名”模块下使用，测试新建了8个，只显示了一个；
“变量名”下拉菜单下的“修改变量名”也无法使用
如图：
![image](https://user-images.githubusercontent.com/53553316/69404287-e8e67080-0d37-11ea-8821-880f14e3ee50.png)

**Comment by zhangleio** [comment]
![image](https://user-images.githubusercontent.com/5885941/69517408-a028f480-0f8f-11ea-8a7c-71e7cc525d87.png)
fixed

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
