### ISSUE TITLE
变量字号更改需求

### ISSUE THREAD

**Issue by grandlin** [tatfook/paracraft#298]
问题：
变量 值在后期的编程过程中，使用会非常频繁，但目前这一块的显示，字体太小，HTML代码也没有可改变字体大小的功能；

需求：
能否加入可调整“大小”的功能？

![image](https://user-images.githubusercontent.com/53553316/69531694-43d5cd00-0faf-11ea-90c3-f573bc98d988.png)

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复)  Thanks
