### ISSUE TITLE
告示牌能否新增“字体大小”的设置功能？

### ISSUE THREAD

**Issue by grandlin** [tatfook/paracraft#301]
如题：告示牌的使用场景比较多，有时候甚至可以直接做为指引，希望能增加“字体大小”调节功能。
或许可以通过新增UI，或是对命令的识别来实现功能，如输入一行“size 16"。
![image](https://user-images.githubusercontent.com/53553316/70038746-bcfaa300-15f3-11ea-8ff0-0990b55db6d3.png)

**Comment by LiXizhi** [comment]
好的， 我们支持下HTML

**Comment by LiXizhi** [comment]
![image](https://user-images.githubusercontent.com/94537/70409965-793aea00-1a88-11ea-8039-5ebcf2569b5a.png)
Fixed in next release (已经修复，等下个版本发布. )  Thanks
