### ISSUE TITLE
【Bug-批量创建】同一类型的方块之间批量创建功能失效，请排查

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/paracraft#302]
#### Details:
1.创建一个新世界，打开E，随意选择一种方块，然后进行放置， 放置后在同一方向间隔20以内的位置再放入另一个。
2.使用shift批量创建功能，观察是否可以快速创建完成  

(目前只会自动批量创建3个,正常应该时全部连接上，即20以内的相同方块，可以批量一次创建完成)

![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/75691769-606a-4c8e-a351-80f47ce97ca3)

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
