### ISSUE TITLE
需求·在电影方块中添加UV动画功能

### ISSUE THREAD

**Issue by yuki1206** [tatfook/paracraft#307]
如图所示，在电影方块中，针对演员新增UV动画功能，使用拍摄电影时，可以让人物有说话的口型和眨眼，增加角色表现力
![image](https://user-images.githubusercontent.com/19921244/70693846-39c70480-1cf9-11ea-9500-a96b986e6be4.png)

**功能需求**

1、基本的功能
eye/mouth  路径+图片名.png  图片长度数值  图片宽度数值  横向偏移数值  纵向偏移数值

2、支持间隔桢和动画间隔功能

3、添加成命令，可以通过@P 来调用，方便作为小游戏的功能

4、相关的功能源于社区版的avatar系统，相关系统中有Emojieye和Emojiemouth相关的两条命令可供查看

**Comment by LiXizhi** [comment]
目前已经支持了  可置换多张贴图。 所以基本功能已经可以实现。 
https://keepwork.com/official/docs/tutorials/create_get_skins
