### ISSUE TITLE
【Bug-template模板】template模板保存时使用相对位置未生效

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/paracraft#309]
### Details:
1.打开软件，更新到最新版本，然后打开一个世界，启用元件库，选中“编程课专用“，使用该模板，然后打开开关，观察显示是否正确
2.自己先创建一个电影方块，然后将人物设置距离电影方块一定的位置，然后ctrl+左键选中保存为template模板，保存成功后，移动主角到不同的位置后放置使用，观察人物是否显示正确，相对位置是否生效

**Expected Result:**
1.相对位置正确，可以正常显示

**Actual Result:**
1.相对位置没生效，显示不对

![image](https://user-images.githubusercontent.com/21214285/70901319-84b48500-2035-11ea-8715-ee2fca5259e6.png)

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
