### ISSUE TITLE
关于新建函数的问题

### ISSUE THREAD

**Issue by grandlin** [tatfook/paracraft#316]
如图所示：
目前“新建函数”后面的括号，只能填写值，无法填写名称，导致无法调用函数。

需求：“新建函数”后面应该有两个空位槽，一个是填名字，一个是填数值。数值的空位槽要设置为“填不填写”都会不影响函数的创建。

![image](https://user-images.githubusercontent.com/53553316/71409945-4a269a00-267e-11ea-90e2-19932c895a78.png)

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
