### ISSUE TITLE
建议更改“复制和被复制体”的名称

### ISSUE THREAD

**Issue by grandlin** [tatfook/paracraft#317]
在行业里，”复制“这个指令都是叫做“克隆”。
同时，为了方便在教案里对概念进行解释和阐述，能不能把”复制“这个词改为”克隆“？
如图所示：
![image](https://user-images.githubusercontent.com/53553316/71467510-02c71780-27fe-11ea-874e-ccab18b0f827.png)
![image](https://user-images.githubusercontent.com/53553316/71467576-49b50d00-27fe-11ea-95f0-0cd0594aff22.png)

**Comment by LiXizhi** [comment]
![image](https://user-images.githubusercontent.com/94537/71507090-34071c80-28be-11ea-95d0-06be9be3791f.png)

Fixed in next release (已经修复，等下个版本发布. )  Thanks
