### ISSUE TITLE
克隆时无法克隆主体此时的状态

### ISSUE THREAD

**Issue by grandlin** [tatfook/paracraft#318]
如图所示：
当克隆到第五个的时候，主体的透明度变成50%，但是克隆出来的角色都无法继承主体此时此刻的状态。
![image](https://user-images.githubusercontent.com/53553316/71467880-22127480-27ff-11ea-910a-350607a9bf48.png)

Scratch的效果如下：
![image](https://user-images.githubusercontent.com/53553316/71468100-da401d00-27ff-11ea-914c-fc43f058c4b4.png)
![image](https://user-images.githubusercontent.com/53553316/71468109-df9d6780-27ff-11ea-8cce-1b19fce7fc64.png)

**Comment by LiXizhi** [comment]
支持透明度了。 
Fixed in next release (已经修复，等下个版本发布. )  Thanks

**Comment by LiXizhi** [comment]
但是隐藏属性不支持Clone  这个是历史问题。
