### ISSUE TITLE
关于代码方块里列表的功能

### ISSUE THREAD

**Issue by grandlin** [tatfook/paracraft#319]
在代码里，有删除、替换等操作，但是在图块拖拽里却没有，请增加。
如图：
![image](https://user-images.githubusercontent.com/53553316/71578789-95d0bc00-2b34-11ea-82f0-35a8e7d79d35.png)

参考：

![image](https://user-images.githubusercontent.com/53553316/71578793-9bc69d00-2b34-11ea-9f6a-f70c01d2780e.png)

**Comment by LiXizhi** [comment]
`字符串%1的长度`改为了`对象%1的长度`

列表的删除并非O(1)算法， 用户使用时心里需要清楚开销， 所以不加为好。 让他们自己写实现吧。
