### ISSUE TITLE
重复执行代码有增加值的功能？

### ISSUE THREAD

**Issue by grandlin** [tatfook/paracraft#320]
重复执行代码有增加值的功能？如图所示，原则上“I"是要增加才会出现如图中的效果，但是发现，只使用”重复10次“居然也有同样的功能，是不是封装过度，哈哈。
现在课程教案正在解释关于”循环变量“的逻辑，所以，为了符合编程的逻辑，请把”重复10次“里面增加值的功能剔除，谢谢。
![image](https://user-images.githubusercontent.com/53553316/71608442-5948a300-2bbc-11ea-814d-2c1e1a0f7f20.png)
![image](https://user-images.githubusercontent.com/53553316/71608449-5ea5ed80-2bbc-11ea-833d-1d2c423047af.png)

**Comment by LiXizhi** [comment]
好的， 重复10次里面的变量，从`i`改为`i_`了。 基本用户不太可能命名为`i_` 

Fixed in next release (已经修复，等下个版本发布. )  Thanks
