### ISSUE TITLE
关于“设置角色的碰撞属性‘

### ISSUE THREAD

**Issue by grandlin** [tatfook/paracraft#322]
经测试，目前，设置角色的”物理半径“、”物理高度“，能改变角色的碰撞效果。希望能增加【宽度】和【长度】的设置。
![image](https://user-images.githubusercontent.com/53553316/71653769-52ab5e80-2d69-11ea-8705-450dca1564a0.png)

**Comment by LiXizhi** [comment]
这个是要做乒乓球那个游戏么？ 因为不支持旋转所以， 宽度和长度意义不大， 并且
方块物理最多1格。 这个我建议还是不要加了。
