### ISSUE TITLE
【急需】请新增一项图块功能

### ISSUE THREAD

**Issue by grandlin** [tatfook/paracraft#323]
目前此功能在代码中能实现，但在图块里却无法实现，请增加。如图：

![image](https://user-images.githubusercontent.com/53553316/71704255-37e1f400-2e14-11ea-9fb7-ea555e355822.png)
![image](https://user-images.githubusercontent.com/53553316/71704260-3dd7d500-2e14-11ea-986e-18a2c03bc300.png)
![image](https://user-images.githubusercontent.com/53553316/71704283-63fd7500-2e14-11ea-9817-f2fcb780db4c.png)

**Comment by LiXizhi** [comment]
看不到图， 文字描述下， 改下标题

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
