### ISSUE TITLE
【急需】请增加“询问并等待回答”的图块功能

### ISSUE THREAD

**Issue by grandlin** [tatfook/paracraft#324]
询问并等待回答功能，可以通过代码实现答案选择窗口，实现鼠标互动，但在图块里，只能通过输入答案，而不能通过点击选择答案。
![image](https://user-images.githubusercontent.com/53553316/71705115-e2f4ac80-2e18-11ea-969a-f8a2140df0b6.png)
![image](https://user-images.githubusercontent.com/53553316/71705119-e7b96080-2e18-11ea-8219-18229fd1e47b.png)
![image](https://user-images.githubusercontent.com/53553316/71705124-f43db900-2e18-11ea-9e47-7289bbc25aca.png)

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
