### ISSUE TITLE
奇怪的“时间”问题

### ISSUE THREAD

**Issue by grandlin** [tatfook/paracraft#328]
如图所示，【等待0秒】这个指令，放置与不放置的执行结果有较大差异，不清楚应该如何解释。
![image](https://user-images.githubusercontent.com/53553316/71711934-1a298480-2e3e-11ea-81e2-d7211a3dd44a.png)

**Comment by LiXizhi** [comment]
wait(0) 相当于释放一次CPU。 所以基本等于wait(0.033). 可以写到百度知道中。
