### ISSUE TITLE
行走偏差的问题

### ISSUE THREAD

**Issue by grandlin** [tatfook/paracraft#329]
ID 4844
点击界面上方的“重新开始”可以将已搭好的桥拆掉。
![image](https://user-images.githubusercontent.com/53553316/71714002-06cee700-2e47-11ea-82c0-f6e0443d8cbb.png)

现在遇到的 问题是，人物行走偏移太大，导致走到中间时会被卡住，暂时查不出原因，请帮忙看一下。
![image](https://user-images.githubusercontent.com/53553316/71713956-dd15c000-2e46-11ea-8a4a-7fdf663f13bb.png)

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
