### ISSUE TITLE
关于克隆与当角色被克隆指令的顺序问题

### ISSUE THREAD

**Issue by grandlin** [tatfook/paracraft#330]
正常的逻辑顺序应该是，先“克隆自己”，接下去才是“当角色被克隆时。。。”
但我们的图块，如果按这个逻辑去放置，将无法执行代码，必须反过来放才可以，如图：
![image](https://user-images.githubusercontent.com/53553316/71792679-a0c7a700-3074-11ea-84b7-63dc93ce8963.png)
![image](https://user-images.githubusercontent.com/53553316/71792684-a6bd8800-3074-11ea-9aea-f1603e4ec4a6.png)

**Comment by LiXizhi** [comment]
这个逻辑没有问题。 
要么先写当XXX， 要么将Clone放到事件和函数中， 保证当当角色被克隆时被先注册了。 比如Scratch是靠点击开始按钮事件。
