### ISSUE TITLE
需求：关于提问并等待回答。

### ISSUE THREAD

**Issue by grandlin** [tatfook/paracraft#331]
因为我们这里使用的是“提问并等待回答”，为了使表述更清晰和标准化，麻烦请把“提问的结果”，更名为“回答”，谢谢~

![image](https://user-images.githubusercontent.com/53553316/71807952-80651000-30a7-11ea-821a-299dff594084.png)

**Comment by grandlin** [comment]
比如这个，A询问B，应该是B做回答，而不是A提问的结果

![image](https://user-images.githubusercontent.com/53553316/71808042-aee2eb00-30a7-11ea-9ac3-9625fd7d53fe.png)

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
