### ISSUE TITLE
【Bug-元件库】元件库需要支持非自身的bmax模型

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/paracraft#335]
### Details:
 因课程需要，需要展示一些模型或者代码内容给合作方，目前是通过元件库直接下载的方式提供；但目前存在问题，问题如下：
1.元件库不支持引用其他bmax模型，即blocks方块里如果引用了其他bmax模型，则无法正常展示。
这里的bmax模型需要支持内部或者外部。

**Comment by LiXizhi** [comment]
OK  我处理下

**Comment by LiXizhi** [comment]
(已经修复 )  Thanks
