### ISSUE TITLE
克隆并移动的问题

### ISSUE THREAD

**Issue by grandlin** [tatfook/paracraft#338]
如图，想要实现这种排列效果，发现Paracraft里操作起来比较烦琐。。

![image](https://user-images.githubusercontent.com/53553316/72061543-1354b300-3311-11ea-9222-aa50ec8c7933.png)

![image](https://user-images.githubusercontent.com/53553316/72061514-03d56a00-3311-11ea-80cb-0dc350e54630.png)

**Comment by LiXizhi** [comment]
这个做法不对， 最好用下面的方式。

![image](https://user-images.githubusercontent.com/94537/72657681-17a06080-39e2-11ea-8f66-96661f1cf924.png)
