### ISSUE TITLE
【Bug-版本同步】使用CAD方块后，新开的paracraft无法正常同步内容

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/paracraft#342]
### Details:
1.先于不同位置安装2份paracraft，如：C:/paracraft及D:/paracraft
2.然后用C盘的paracraft登录账号，创建新世界A，使用CAD方块，然后保存世界进行分享
3.然后使用D盘的paracraft登录账号，然后打开新创建的世界A，进入世界后，打开文件所在位置，进行查看，发现路径不对。

**Attachment:**
![image](https://user-images.githubusercontent.com/21214285/72231914-f2ce7680-35f8-11ea-9d8a-a7fe2f9e1985.png)

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
