### ISSUE TITLE
【Bug-音频切换】当音频设备进行切换时，paracraft需要能识别自动切换，请优化实现

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/paracraft#345]
### Details:
    
目前有用户使用paracraft时遇到了无法播放声音的情况，其操作是先使用耳机，后切换到音响，发现没有声音，需要重启paracraft才行。请优化处理方式，当发现音频设备变化时，能自动切换。

![image](https://user-images.githubusercontent.com/21214285/72307450-49998600-36b5-11ea-9709-a311f8002ac4.png)

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
