### ISSUE TITLE
克隆角色时出现的倍增问题

### ISSUE THREAD

**Issue by grandlin** [tatfook/paracraft#346]
1.当演员1被点击时，发送广播消息A；
![image](https://user-images.githubusercontent.com/53553316/72593188-53361e80-393f-11ea-9ba3-42011b2c83cd.png)
2.当演员2接收到广播消息时，克隆自己；
![image](https://user-images.githubusercontent.com/53553316/72593274-8aa4cb00-393f-11ea-86e5-4aa64dd7f5ae.png)
问题描述：
当演员1被点击时，演员2克隆了1只；
再次点击时，演员2克隆了2只；
再次点击时，演员2克隆了4只；
再次点击时，演员2克隆了8只；
再次点击时，演员2克隆了16只；

应该是每次只克隆1只的，不知为何是克隆倍数增长的呢？
这是点了4次后的效果：
![image](https://user-images.githubusercontent.com/53553316/72593501-1a4a7980-3940-11ea-96c2-54685a28801e.png)

**Comment by LiXizhi** [comment]
每个clone的对象， 也会收到这个消息， 所以倍增了。

**Comment by grandlin** [comment]
这样的设置好像不太合理。

**Comment by LiXizhi** [comment]
要验证下， Scratch是否也是这样的。

**Comment by LiXizhi** [comment]
Scratch和我们的逻辑是一样。所以还是维持目前的逻辑吧 这个符合正常的逻辑。 
![image](https://user-images.githubusercontent.com/94537/72657493-efaffd80-39df-11ea-949f-dd1227d6d985.png)
