### ISSUE TITLE
新的世界类型：机构专用世界

### ISSUE THREAD

**Issue by azothli** [tatfook/paracraft#349]
作为一个独立的世界类型，该类型不随着另存、fork等行为更改。

该世界仅供 vip、t进入使用。

非vip、t进入时候提示，“您未获得该内容的访问权限。”

新增指令/setvipworld   将一个普通世界升级为vip世界，保存后生效，该行为不可逆。

**Comment by azothli** [comment]
指令按照已有规则，xishi可自行制定。

功能上线后，keepwork继续增加该类型项目的标识。

教研急须，烦请优先！

**Comment by LiXizhi** [comment]
```
/setworldinfo -isVipWorld true    
```

Fixed in next release (已经修复，等下个版本发布. )  Thanks
