### ISSUE TITLE
探索APP UI

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/paracraft#35]

**Comment by Kvaya** [comment]
**背景：**
探索APP放在商户购买的设备上的Paracraft中，商户通过操作设备上的Paracraft,让小孩子可以玩Paracraft上的游戏。

**解决方案：**
整体Paracraft UI放在SVN “探索APP”文件夹中。如图：

![image](https://user-images.githubusercontent.com/39363297/51306643-d6950980-1a78-11e9-8ed5-a552e63815b1.png)

上面图红色框中。

**备注：**
![image](https://user-images.githubusercontent.com/39363297/51306574-9e8dc680-1a78-11e9-8bc5-181d9a9a056e.png)
启动Paracraft后，点击任意地方打开探索APP，探索APP的主页面和进入游戏界面都是全屏的

**Comment by Kvaya** [comment]
设计稿参考：
![app](https://user-images.githubusercontent.com/39363297/51467425-7cad8000-1da7-11e9-94e8-bdd5b5757d76.png)

设计稿地址：
![image](https://user-images.githubusercontent.com/39363297/51467456-8f27b980-1da7-11e9-8ee4-5f2e71458bf3.png)

**Comment by Kvaya** [comment]
备注：
探索主页内的项目是上下滑动的方式看下面更多的游戏

**Comment by Kvaya** [comment]
探索主页对应的英文显示参考：
![r wh9 asqh bhkl8yw ylu](https://user-images.githubusercontent.com/39363297/51520016-96110380-1e5d-11e9-9fb0-1664bc655bfd.png)

**Comment by Kvaya** [comment]
设计稿地址：
![image](https://user-images.githubusercontent.com/39363297/51598576-ced1db00-1f38-11e9-96af-cc4b57a5aff5.png)

**Comment by Kvaya** [comment]
备注：
排序分别是：综合、热门、最新；
搜索框内搜索ID是针对整个app而言；比如在“对战”页面，输入ID后，搜索结果显示出来，但是从全app搜到的，左侧”精选到收藏“框不高亮就好

**Comment by Kvaya** [comment]
![image](https://user-images.githubusercontent.com/39363297/51727410-edee7b00-20a6-11e9-9479-b9b2139c5cd0.png)
其中里面”双人"游戏改为“多人”，这些类别在“收藏”上面，如图：
![image](https://user-images.githubusercontent.com/39363297/51727542-681eff80-20a7-11e9-9734-e7a0f603283e.png)

**Comment by Kvaya** [comment]
“修改密码”功能放在“设置密码”和“输入密码”页面上去；
“投币设置”页面上没有“修改密码”功能

**Comment by Kvaya** [comment]
背景：
![fmznfpqkx26zj jzu j7 jg](https://user-images.githubusercontent.com/39363297/52758023-be95b300-3041-11e9-983e-1391bd040f89.png)

解决方案：
设计稿如下：
![image](https://user-images.githubusercontent.com/39363297/52758060-e553e980-3041-11e9-958e-851b2ceee3fc.png)
设计稿地址：
![image](https://user-images.githubusercontent.com/39363297/52758080-f866b980-3041-11e9-922a-9cc26d3e28d7.png)

文件是“探索APP(1)-1”

**Comment by Sandu1213** [comment]
样式调整与设计图一致
