### ISSUE TITLE
paracraft菜单调整方案

### ISSUE THREAD

**Issue by azothli** [tatfook/paracraft#355]
根据年前讨论，方案做好，看看是谁来开发调整，文档在附在下面。

**Comment by azothli** [comment]
[[Paracraft]菜单调整方案_liyu_20200213.xlsx](https://github.com/tatfook/paracraft/files/4194380/Paracraft._liyu_20200213.xlsx)

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
