### ISSUE TITLE
【优化-账号登陆】登陆页面输入时需要支持tab键切换，方便用户使用

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/paracraft#357]
![image](https://user-images.githubusercontent.com/21214285/74637746-8e797680-51a5-11ea-909e-ab2a990e1629.png)
![image](https://user-images.githubusercontent.com/21214285/74637798-a5b86400-51a5-11ea-9c6b-d4091147df85.png)

**Comment by LiXizhi** [comment]
@onedou 

将editbox 放在 <form>用支持tab了
<form name="ParacraftUserLogin">
</form>

**Comment by onedou** [comment]
已修复，paracraft测试

**Comment by Sandu1213** [comment]
已支持。
