### ISSUE TITLE
关于3维坐标显示的问题

### ISSUE THREAD

**Issue by grandlin** [tatfook/paracraft#360]
由于世界里有严格的坐标方向区分，比如人物搭建时，脸部一定要朝向X轴，在代码控制向前移动时，才能有正确的效果，否则就还得多增加一行旋转指令。
为了方便用户搭建和创作，还是建议有个三维坐标显示可能会比较合理，或者是可以让用户自行选择开或关。
![微信截图_20200305134504](https://user-images.githubusercontent.com/53553316/75951915-37370e00-5ee8-11ea-9e29-c6aa740c63ce.png)

**Comment by LiXizhi** [comment]
F3中可以看方向。 
或者Ctrl+左键， 也能看方向。 

这个暂时先不加了。
