### ISSUE TITLE
透明方块在显示背后的物品时，渲染效果不太好。

### ISSUE THREAD

**Issue by grandlin** [tatfook/paracraft#361]
透明方块显示背后的面，渲染效果不太好，会出现视觉上的破损。如图
![image](https://user-images.githubusercontent.com/53553316/76061495-9bc49c80-5fbe-11ea-97cb-23833bbe8e03.png)

**Comment by LiXizhi** [comment]
这个技术上暂时没有好的方法。 否则会严重影响性能。
