### ISSUE TITLE
拉杆无法启动CAD方块

### ISSUE THREAD

**Issue by grandlin** [tatfook/paracraft#363]
如图所示：
![image](https://user-images.githubusercontent.com/53553316/76065196-1a710800-5fc6-11ea-8807-83a8266488d9.png)
![image](https://user-images.githubusercontent.com/53553316/76065224-278df700-5fc6-11ea-98e8-c4d1f505ecc7.png)

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
