### ISSUE TITLE
紧急：CAD原点和坐标问题！

### ISSUE THREAD

**Issue by grandlin** [tatfook/paracraft#365]
由于CAD需要精确的数值运算，在Paracraft世界里无法做到像Npl Cad独立软件那样，有网格作为参考，那么所有数值将无法准确计算。如图所示，出生点就是原点，数值为0，然后每一个格数值加1，非常清晰的规则：
[image](https://user-images.githubusercontent.com/53553316/76070629-d08d1f80-5fcf-11ea-8370-bffa55c2cbb4.png)

再如，我要做一个有导角的图形，在Paracraft的世界里，实现起来将非常困难。
![image](https://user-images.githubusercontent.com/53553316/76070974-6aed6300-5fd0-11ea-8cee-a125d56e048c.png)

**Comment by LiXizhi** [comment]
好的， 我加下各自显示。 

@zhangleio 倒角单独建立一个issue给zhangleio, chenjinxian.

**Comment by LiXizhi** [comment]
![image](https://user-images.githubusercontent.com/94537/76182322-6490fe00-61ff-11ea-843f-188951f9091c.png)
Fixed in next release (已经修复，等下个版本发布. )  Thanks
