### ISSUE TITLE
紧急：CAD方块缓存问题

### ISSUE THREAD

**Issue by grandlin** [tatfook/paracraft#366]
这个黄色镂空模型是在中间的CAD里搭建的，但是打开其他两个CAD模块，不运行代码的情况下，显示的都是同一个模型

![image](https://user-images.githubusercontent.com/53553316/76072839-a3db0700-5fd3-11ea-9a74-f45b4f437b62.png)

![image](https://user-images.githubusercontent.com/53553316/76072874-b0f7f600-5fd3-11ea-988d-c73a7499d133.png)

**Comment by LiXizhi** [comment]
这个不是BUG。 每个CAD方块需要指定不同的角色名称。 不然重名了， 就是一个文件，看谁最后执行了。

**Comment by grandlin** [comment]
啊，原来是这样，明白了。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Li, Xizhi <notifications@github.com&gt;
发送时间: 2020年3月6日 18:47
收件人: tatfook/paracraft <paracraft@noreply.github.com&gt;
抄送: grandlin <1520288484@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[tatfook/paracraft] 紧急：CAD方块缓存问题 (#366)




这个不是BUG。 每个CAD方块需要指定不同的角色名称。 不然重名了， 就是一个文件，看谁最后执行了。

**Comment by LiXizhi** [comment]
我加了提示， 如果用户没有命名CAD方块， 目前外网会提示用户一次。
