### ISSUE TITLE
元件库的动作识别需求

### ISSUE THREAD

**Issue by grandlin** [tatfook/paracraft#368]
现在在增加元件库里一些汽车的模型，考虑到用户体验，我们会将轮子旋转的动画预设进X文件里再进行上传，但是在做轮子旋转动画时遇到了困难：
1.关键帧或轮子无法组合复制；
2.使用wheel指令，X文件无法识别此动作指令；
因为汽车模型有很多种，后期会陆续增加，为了提高制作的效率，提以下需求：
能否使轮子和其动画可同时被复制，或者让X文件可以识别wheel指令。

**Comment by LiXizhi** [comment]
如果是我们自己做的化， 可以从电影方块中导出任意动作， 详情请见教学视频。 
可以导出带4号动作的汽车模型。 建议所有的动物也这样处理， 至少包含走路和待机动作。 

如果不清楚， 可以提百度知道
