### ISSUE TITLE
【需求-图块代码】目前通过图块代码放置颜色方块后，无法设置颜色，建议优化一下

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/paracraft#385]
### Details:
- 目前放置颜色方块的效果：
  
![image](https://user-images.githubusercontent.com/21214285/76936298-acb1ce00-692d-11ea-88fd-775a895ccf38.png)

- 预期效果：
![image](https://user-images.githubusercontent.com/21214285/76936507-04e8d000-692e-11ea-92f1-e3c9236e1f7e.png)

**Comment by LiXizhi** [comment]
方案1：可以用命令cmd 
方案2：
![image](https://user-images.githubusercontent.com/94537/77145554-ddc40700-6ac3-11ea-8f54-ce4f5e3188a4.png)

方案2等下个版本
