### ISSUE TITLE
【Bug-代码方块】多人联网时，从机执行代码方块的代码，看不到效果

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/paracraft#391]
### Details:
1.在代码方块里添加代码后，开启多人联网功能，然后从机通过开关执行代码，观察显示情况
2.在电影方块里添加bmax模型，然后通过代码方块控制循环播放，开启多人联网后，从机打开开关，观察显示情况

![image](https://user-images.githubusercontent.com/21214285/77043028-b273e600-69f7-11ea-857c-90325a2a52c6.png)

![image](https://user-images.githubusercontent.com/21214285/77043120-cfa8b480-69f7-11ea-8ef3-d718a243f29e.png)

**Comment by LiXizhi** [comment]
fixed
