### ISSUE TITLE
图块编程指令优化需求

### ISSUE THREAD

**Issue by grandlin** [tatfook/paracraft#393]
目前缺少指令移动到某个坐标点。
”瞬移到“与”设置角色位置“两条指令效果一样，能否将”瞬移到“改为”移动到“并加入行走动作？
如图：
![image](https://user-images.githubusercontent.com/53553316/77151717-82991100-6ad1-11ea-9aea-6b2b6572f4e1.png)
![image](https://user-images.githubusercontent.com/53553316/77151912-e15e8a80-6ad1-11ea-8a1a-0e92305ef46a.png)

**Comment by LiXizhi** [comment]
应为速度是未知的， 所以暂时不会提供这个功能。 用户需要自己算时间
