### ISSUE TITLE
CAD圆柱生成失败，请检测

### ISSUE THREAD

**Issue by grandlin** [tatfook/paracraft#394]
如图所示：
![image](https://user-images.githubusercontent.com/53553316/77152309-a6a92200-6ad2-11ea-9d9d-eedd50797226.png)

**Comment by grandlin** [comment]
补充：
两个以上的布尔运算也无法运行，如图
![image](https://user-images.githubusercontent.com/53553316/77152721-744bf480-6ad3-11ea-926a-a6213a664e5b.png)

**Comment by LiXizhi** [comment]
fixed
