### ISSUE TITLE
同角色复制骨骼关键帧仍无法使用。

### ISSUE THREAD

**Issue by ouyc** [tatfook/paracraft#395]
ID 4801
如图所示，要复制A轮胎的“旋转关键帧”给B轮胎，提示“复制成功”，但并产生无实际效果。
![1.jpg](https://images.zenhubusercontent.com/5ac352dc4b5806bc2bcd6b02/d34cbc1c-580e-4365-8505-84d0ff068ae5)
![2.jpg](https://images.zenhubusercontent.com/5ac352dc4b5806bc2bcd6b02/28f59873-3bbf-4b3d-b80d-a38cf9273b54)

**Comment by LiXizhi** [comment]
目前只有同名骨骼可以复制。 
你可以做好一个人物的4个轮胎， 然后一次性复制到另外一个角色。 
注意骨骼名字要一致。 这样就不用一个一个复制了。
