### ISSUE TITLE
NPL CAD的收费课程

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/paracraft#43]

**Comment by shirleyluo1130** [comment]
**一、课程包url**

https://keepwork.com/l/teacher/package/9

**二、包含13个课程，课程内容url如下：**

1、NPL CAD安装与基本操作 https://keepwork.com/lesson9527/lessons/NPL_CAD/Installation_and_basic_operation

2、NPL CAD基本命令与实例 https://keepwork.com/lesson9527/lessons/NPL_CAD/Basic_commands_and_examples

3、NPL编程基础知识：语法  https://keepwork.com/lesson9527/lessons/NPL_CAD/NPL_programming_basic_grammer

4、程序的本质 https://keepwork.com/lesson9527/lessons/NPL_CAD/Nature_of_programming

5、数字与数学 https://keepwork.com/lesson9527/lessons/NPL_CAD/Numbers_and_Mathematics

6、变量与名字 https://keepwork.com/lesson9527/lessons/NPL_CAD/Variables_and_names

7、字符串与文字 https://keepwork.com/lesson9527/lessons/NPL_CAD/Strings_and_texts

8、表与数组 https://keepwork.com/lesson9527/lessons/NPL_CAD/Tables_and_arrays

9、函数 https://keepwork.com/lesson9527/lessons/NPL_CAD/Function

10、内置函数 https://keepwork.com/lesson9527/lessons/NPL_CAD/Built_in_function

11、NPL CAD实例分析1 https://keepwork.com/lesson9527/lessons/NPL_CAD/NPLCAD_example_1

12、NPL CAD实例分析2 https://keepwork.com/lesson9527/lessons/NPL_CAD/NPLCAD_example_2

13、NPL CAD对学习编程的建议 https://keepwork.com/lesson9527/lessons/NPL_CAD/Advice_on_learning_programming

**Comment by shirleyluo1130** [comment]
待添加的内容，包含：Paracraft世界、Quizzes、技能点信息
