### ISSUE TITLE
【天梯-keepwork】项目展示调整，增加评分的显示

### ISSUE THREAD

**Issue by azothli** [tatfook/paracraft#45]
![image](https://user-images.githubusercontent.com/22001356/50826509-c42f1780-1376-11e9-9587-e7ee07b5772a.png)

在评分人数<8的时候，显示N/A,鼠标悬停显示“上位收集到足够的评价”
大于等于8 则正常显示分数，保留小数点后一位，末位四舍五入。

**Comment by Sandu1213** [comment]
页面已经实现，待评分实现后，再验证存在评分的效果

**Comment by Sandu1213** [comment]
存在评分时，展示不对，请调整
