### ISSUE TITLE
Paracraft 移动APP发布

### ISSUE THREAD

**Issue by ouyc** [tatfook/paracraft#51]
@LiXizhi commented on [Fri Nov 23 2018](https://github.com/tatfook/devops/issues/21)

现在需要将我们的AndroidAPP以大富网络的名义，发到国内外的主流平台上。 
PC版外加发到Steam.  ICP和文网文证书可以问冯冯要. 

- 手机渠道:  应用宝， 华为应用商店， google app store 等
- PC渠道：Steam，等

---

@Xuntian commented on [Wed Dec 12 2018](https://github.com/tatfook/devops/issues/21#issuecomment-446478162)

@LiXizhi 华为app商城去年已经发布过了，需要找到之前的账号，我这边的可能需要注销

---

@Xuntian commented on [Wed Jan 02 2019](https://github.com/tatfook/devops/issues/21#issuecomment-450781632)

华为app商店已经成功发布了

---

@LiXizhi commented on [Wed Jan 02 2019](https://github.com/tatfook/devops/issues/21#issuecomment-450783974)

好的， 其它的也继续发布， 首次审核比较难， 更新比较容易。

**Comment by Xuntian** [comment]
目前paracraft移动app发布情况，计划在华为，小米，百度，腾讯和谷歌5个平台上发布，目前华为已经上线，百度还在审核，腾讯存在公司认证重复问题，小米因官方禁止应用内下载和更新暂时停止发布，谷歌因不支持国内的信用卡支付注册费用暂时放弃
