### ISSUE TITLE
【探索APP dashboard】商户在我们这买了一些设备，需要在后台对这些设备进行管理

### ISSUE THREAD

**Issue by Kvaya** [tatfook/paracraft#92]
背景：
Paracraft 探索APP是安装在我们平台出售的设备上，商户购买了这些设备，我们后台要记录这些设备的设备码，是被谁购买的，这台设备上Paracraft系统密码是多少

解决方案：
paracraft 探索APP 的后台有一个“设备管理”页面，
记录下设备的设备码、购买者、Paracraft的系统密码（商户用于修改支付密码）。
![image](https://user-images.githubusercontent.com/39363297/51590565-5f9ebb80-1f25-11e9-988c-d53d648ffa00.png)

**Comment by Kvaya** [comment]
设备新增，必填项：
![image](https://user-images.githubusercontent.com/39363297/51722624-fb006f80-2090-11e9-9909-49f2c50fb643.png)
新增时，必填项分别是：设备码、设备购买价格、设备系统密码、购买者电话(假设没有电话，有其他联系方式存着也可以，方便日后维护)

**Comment by Kvaya** [comment]
建议“设备”管理页，设备列表中，“游戏币数量”改为“设备卖时含有的游戏币”

**Comment by Sandu1213** [comment]
存在的bug:
1.直接点击新增，未添加任何内容，提示“添加成功”，且多了一条无用数据
2.新增时，对于必填项需要进行验证
3.新增时，缺少购买时间字段的设置（购买时间精确到日期？） @Kvaya 
4.新增时，如果设备号相同，提示语不合理
![image](https://user-images.githubusercontent.com/21214285/51723220-55023480-2093-11e9-9e97-23a1936b63cb.png)
5.编辑修改时，也缺少购买时间字段
6.编辑时，对于同名的设备号提示语也需要进行调整
