### ISSUE TITLE
【探索APP dashboard】探索APP中商户输入激活码用于充值，后台需要生成一些激活码

### ISSUE THREAD

**Issue by Kvaya** [tatfook/paracraft#93]
背景：
商户买了设备后，Paracraft软件需要通过输入激活码用于充值，运营人员需在后台生成一些含有一定面额的激活码提供给商户。

解决方案：
探索APP的后台有一个“激活码”页面，新增一些含有定价的激活码，记录生成好的激活码。
![image](https://user-images.githubusercontent.com/39363297/51305815-dac02780-1a76-11e9-9d93-83f67fe810db.png)

**Comment by Kvaya** [comment]
建议激活码页面，“游戏币数量”改为“含有游戏币数量”

**Comment by Sandu1213** [comment]
存在的bug:
1.生成激活码不需要默认值
![image](https://user-images.githubusercontent.com/21214285/51728193-5723bd80-20aa-11e9-9464-47c36b4d2c6a.png)
2.默认排序不对
![image](https://user-images.githubusercontent.com/21214285/51728436-327c1580-20ab-11e9-8cd1-75b78f6b67f1.png)
3.全选不能导出所有数据
![image](https://user-images.githubusercontent.com/21214285/51728482-5c353c80-20ab-11e9-9e00-c5b9d49c53c9.png)
4.激活码生成规则需要乱序
![image](https://user-images.githubusercontent.com/21214285/51728570-c221c400-20ab-11e9-87d8-d51bfe2b04c9.png)
5.生成数量大于1000就失败了，请调整
![image](https://user-images.githubusercontent.com/21214285/51728711-26dd1e80-20ac-11e9-8ea2-ce4896cbdf84.png)

**Comment by Kvaya** [comment]
在激活码列表中加一项“使用情况”，使用情况分：已使用、未使用，默认显示未使用，
假设在“消费记录”中该激活码被激活了，在“激活码”页面中的，激活码使用情况是“已使用”
