### ISSUE TITLE
【探索APP dashboard】探索APP后台的“购买记录”页面

### ISSUE THREAD

**Issue by Kvaya** [tatfook/paracraft#94]
背景：
激活码有些是被代理商买走一批，有的是被商户买走一批。运营人员需在后台能看到哪些激活码是被谁买走了，这些激活码各自含有多少游戏币可使用。

解决方案：
探索APP后台有一个“购买记录”页面，记录这些激活码是被谁买走了，含有多少游戏币，激活码是花多少钱买的。
![image](https://user-images.githubusercontent.com/39363297/51590619-9248b400-1f25-11e9-9744-3f51dbbe16ab.png)

**Comment by Kvaya** [comment]
建议“购买记录”页面，“价格”改为“激活码售价”，“游戏币数量”改为“含有游戏币数量”；

新增时，必填项：
![image](https://user-images.githubusercontent.com/39363297/51723671-fb026e80-2094-11e9-8d95-27ff39e96319.png)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/51729766-057e3180-20b0-11e9-8a8a-f6f468dbb5d7.png)
