### ISSUE TITLE
【探索APP dashboard】探索APP后台“消费记录”页面

### ISSUE THREAD

**Issue by Kvaya** [tatfook/paracraft#95]
背景：
商户买走激活码后，会在Paracraft上进行充值，运营人员需记录激活码是激活哪台设备，激活了多少游戏币

解决方案：
探索APP的后台有一个“消费记录”页面，记录激活码激活哪台设备，与此同时激活多少游戏币。
![image.png](https://images.zenhubusercontent.com/5afd3a0d4b5806bc2bd3861a/4add90dd-b4a2-4c28-a53c-4a385cb98fbb)

**Comment by Sandu1213** [comment]
待探索App出来后再验证

**Comment by Kvaya** [comment]
建议“消费记录”页面，“游戏币数量”改为“激活游戏币数量”
